/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Total() {
    return (
        <div className="min-w-[320px] items-start border border-[color:var(--colors-border-border-secondary,#1F242F)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 flex w-[349px] max-w-full grow flex-col mx-auto px-5 py-6 rounded-xl border-solid max-md:mt-6">
            <div className="self-stretch text-neutral-100 text-base font-semibold leading-[150%] w-full mx-1">
                Total customers
            </div>
            <div className="items-start self-stretch flex justify-between gap-4 mt-6 mx-1">
                <div className="items-start flex flex-col w-[157px]">
                    <div className="self-stretch text-neutral-100 text-4xl font-semibold leading-[122.22%] tracking-tighter w-full">
                        2,420
                    </div>
                    <div className="items-start self-stretch flex justify-between gap-2 mt-4">
                        <div className="justify-between items-start self-stretch flex gap-0.5">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/69dd714c-f8d5-4682-aff9-0f2e1f6116d5?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <div className="text-green-400 text-center text-sm font-medium leading-[142.86%] self-stretch">
                                40%
                            </div>
                        </div>
                        <div className="overflow-hidden text-neutral-400 text-ellipsis text-sm font-medium leading-[142.86%] self-stretch">
                            vs last month
                        </div>
                    </div>
                </div>
                <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/29b7e5aa-581a-430f-9558-59cd904e45b0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                    className="aspect-[2] object-cover object-center w-32 overflow-hidden shrink-0 mt-4"
                />
            </div>
        </div>
    );
}
