export default function PlusSquareIcon() {
  return (
    <svg
      fill="currentColor"
      height="32"
      width="32"
      viewBox="0 0 64 64"
      style={{ display: "inlineBlock", verticalAlign: "middle" }}
    >
      <g>
        <line
          strokeWidth="2"
          strokeMiterlimit="10"
          x1="32"
          y1="50"
          x2="32"
          y2="14"
          fill="none"
          stroke="currentColor"
        >
          <line
            strokeWidth="2"
            strokeMiterlimit="10"
            x1="32"
            y1="50"
            x2="32"
            y2="14"
            fill="none"
            stroke="currentColor"
          ></line>
        </line>
        <line
          strokeWidth="2"
          strokeMiterlimit="10"
          x1="14"
          y1="32"
          x2="50"
          y2="32"
          fill="none"
          stroke="currentColor"
        >
          <line
            strokeWidth="2"
            strokeMiterlimit="10"
            x1="14"
            y1="32"
            x2="50"
            y2="32"
            fill="none"
            stroke="currentColor"
          ></line>
        </line>
      </g>
      <rect
        x="1"
        y="1"
        strokeWidth="2"
        strokeMiterlimit="10"
        width="62"
        height="62"
        fill="none"
        stroke="currentColor"
      ></rect>
    </svg>
  )
}
