/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function ImageComponent() {
  return (
    <figure className="aspect-square">
      <img
        loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/72bf3c94-9d3d-4a13-9d87-0e3b0810836f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
        className="object-cover object-center w-5"
        alt="Description of the image"
      />
    </figure>
  );
}
