/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { useState } from "react";

export default function Table() {
    const [isChecked, setIsChecked] = useState(() => null);

    const [handleCheckboxChange, setHandleCheckboxChange] = useState(() => null);

    const [newField0, setNewField0] = useState(() => null);

    return (
        <div className="items-start self-stretch flex flex-col">
            <div className="items-start self-stretch flex w-full justify-between gap-5 px-5 max-md:max-w-full max-md:flex-wrap">
                <div className="items-start self-center flex gap-3 my-auto max-md:justify-center">
                    <div className="justify-between items-start border border-[color:var(--component-colors-components-buttons-secondary-button-secondary-border,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-stretch flex w-[107px] max-w-full gap-1.5 pl-4 pr-3.5 py-2.5 rounded-lg border-solid">
                        <div className="text-neutral-300 text-sm font-semibold leading-[142.86%] self-stretch">
                            All time
                        </div>
                        <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/dd7453ff-f0b5-442d-abd9-85f376f50081?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                            className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                        />
                    </div>
                    <div className="justify-between items-start border border-[color:var(--component-colors-components-buttons-secondary-button-secondary-border,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-stretch flex w-[129px] max-w-full gap-1.5 pl-4 pr-3.5 py-2.5 rounded-lg border-solid">
                        <div className="text-neutral-300 text-sm font-semibold leading-[142.86%] self-stretch">
                            US, AU, +4
                        </div>
                        <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bbcda223-2b13-4ee6-9f17-adc23a11d633?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                            className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                        />
                    </div>
                    <div className="justify-between items-start border border-[color:var(--component-colors-components-buttons-secondary-button-secondary-border,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-stretch flex w-[134px] max-w-full gap-1.5 pl-3.5 pr-4 py-2.5 rounded-lg border-solid">
                        <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9034ab38-8974-43dc-85ac-2f7ab0c0d34d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                            className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                        />
                        <div className="text-neutral-300 text-sm font-semibold leading-[142.86%] self-stretch">
                            More filters
                        </div>
                    </div>
                </div>
                <div className="items-center self-stretch border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 flex w-80 max-w-full flex-col px-3.5 py-2.5 rounded-lg border-solid">
                    <div className="items-start self-stretch flex justify-between gap-2">
                        <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1c755ced-7e97-4ae5-b705-4c18f9e1c05b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                            className="aspect-square object-cover object-center w-5 overflow-hidden self-center shrink-0 my-auto"
                        />
                        <div className="overflow-hidden text-zinc-500 text-ellipsis text-base leading-[150%] self-stretch max-w-[284px] grow shrink-0 basis-auto">
                            Search
                        </div>
                    </div>
                </div>
            </div>
            <div className="items-start self-stretch border border-[color:var(--colors-border-border-secondary,#1F242F)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 flex w-full flex-col mt-6 rounded-xl border-solid max-md:max-w-full">
                <div className="items-start self-stretch flex w-full gap-0 px-5 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
                    <div className="items-start self-stretch flex flex-col w-[242px]">
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 flex w-full flex-col px-5 py-3 border-b border-solid">
                            <div className="flex w-[107px] max-w-full items-start gap-3 ml-1">
                                <label className="items-center flex">
                                    <input
                                        type="checkbox"
                                        className="mr-2.5"
                                        checked={isChecked ? "checked" : ""}
                                        onChange={(event) => handleCheckboxChange()}
                                    />
                                    <span className="text-base text-zinc-800" />
                                </label>
                                <div className="items-start self-stretch flex justify-between gap-1 mt-px">
                                    <div className="text-neutral-400 text-xs font-medium leading-[150%] self-stretch">
                                        Company
                                    </div>
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/409fad5d-2fe3-4735-85ea-fb26fbe15289?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="aspect-square object-cover object-center w-4 overflow-hidden shrink-0 mt-px"
                                    />
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[174px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <input type="checkbox" className="mt-4" />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/26a42b98-36ab-4dc6-a5e9-c0b73b735df0?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Catalog
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        catalogapp.io
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex gap-3 px-5 py-4 border-b border-solid max-md:justify-center">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/32250584-ff6f-4849-93ef-54bb0f9a0bf3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 justify-center items-center overflow-hidden self-center shrink-0 my-auto"
                            />
                            <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/442224c5-eb91-4a6e-9715-b1068168b84f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="absolute h-full w-full object-cover object-center"
                                />
                                <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                            </div>
                            <div className="items-start self-stretch flex flex-col">
                                <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                    Capsule
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    getcapsule.com
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[171px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4fbac1ad-d184-4cfd-ae9f-dcfa0274777f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-5 justify-center items-center overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/13ccb015-b9c9-4ba5-b80c-75283e9e1592?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Command+R
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        cmdr.ai
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[177px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <div className="border border-[color:var(--colors-border-border-primary,#333741)] self-center flex w-5 h-5 flex-col my-auto rounded-md border-solid" />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/16a13d32-7dbf-4efe-a755-92f0729aca0f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Hourglass
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        hourglass.app
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[161px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <div className="border border-[color:var(--colors-border-border-primary,#333741)] self-center flex w-5 h-5 flex-col my-auto rounded-md border-solid" />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d86ea9a-3172-49f1-bb54-9e88c514aad2?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Layers
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        getlayers.io
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[159px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1bf160c2-555d-4a47-85d2-af911e04a74b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-5 justify-center items-center overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bf9383f0-c577-4ac4-940a-df4c601026f8?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Quotient
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        quotient.co
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex grow flex-col px-5 py-4 border-b border-solid">
                            <div className="flex w-[175px] max-w-full items-start gap-3 ml-1 max-md:justify-center">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/046547c7-cf18-495c-9dc0-3d61f4935aab?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-5 justify-center items-center overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="flex-col justify-center items-center overflow-hidden relative flex aspect-square w-10 shrink-0">
                                    <img
                                        loading="lazy"
                                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/09caf2da-e21d-40fc-a621-ae089600cb44?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                        className="absolute h-full w-full object-cover object-center"
                                    />
                                    <div className="relative self-stretch border-[color:var(--component-colors-components-avatars-avatar-contrast-border,rgba(255,255,255,0.12))] flex w-full h-10 flex-col rounded-full border-[0.75px] border-solid" />
                                </div>
                                <div className="items-start self-stretch flex flex-col">
                                    <div className="text-neutral-100 text-sm font-medium leading-[142.86%]">
                                        Sisyphus
                                    </div>
                                    <div className="text-neutral-400 text-sm leading-[142.86%]">
                                        sisyphus.com
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="items-start self-stretch flex flex-col w-[136px]">
                        <div className="text-neutral-400 text-xs font-medium leading-[150%] self-stretch items-center border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 w-full px-5 py-3.5 border-b border-solid">
                            License use
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-[66px] h-2 flex-col rounded-full" />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-[58px] h-2 flex-col rounded-full" />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-7 h-2 flex-col rounded-full" />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-5 h-2 flex-col rounded-full" />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex grow flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-[43px] h-2 flex-col rounded-full" />
                            </div>
                        </div>
                    </div>
                    <div className="items-start self-stretch flex flex-col w-[129px]">
                        <div className="text-neutral-400 text-xs font-medium leading-[150%] self-stretch items-center border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 w-full px-5 py-3.5 border-b border-solid">
                            Status
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[81px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/05a6efb7-e4bc-4fea-b00c-96c8e819d3e4?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Customer
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[74px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/27dd08c4-a172-4479-85a3-47967bd1078a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Churned
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[81px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fffdb9ff-e1a2-47e5-9cc7-d7749732f14d?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Customer
                                </div>
                            </div>
                            <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                                <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-4 rounded-full">
                                    <div className="bg-violet-400 self-stretch flex w-full h-2 flex-col rounded-full" />
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-8 border-b border-solid">
                            <div className="bg-zinc-700 self-center flex w-[88px] max-w-full flex-col pr-5 rounded-full">
                                <div className="bg-violet-400 flex w-[35px] h-2 flex-col rounded-full" />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[81px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4409122a-9c79-498d-8eb0-2e1a2b21c7c7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Customer
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[74px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/39525a8f-0368-489f-a54e-76eb74e4a681?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Churned
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[81px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/be741984-2b33-408e-9b16-c78079b64547?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Customer
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex grow flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start border border-[color:var(--colors-border-border-primary,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 self-center flex w-[81px] max-w-full gap-1 px-1.5 py-0.5 rounded-md border-solid">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c2fe9b62-8fe1-4771-8623-fe84c6fce431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-square object-cover object-center w-2 overflow-hidden self-center shrink-0 my-auto"
                                />
                                <div className="text-neutral-300 text-center text-xs font-medium leading-[150%] self-stretch">
                                    Customer
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="items-start self-stretch flex flex-col w-[172px]">
                        <div className="text-neutral-400 text-xs font-medium leading-[150%] self-stretch items-center border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 w-full px-5 py-3.5 border-b border-solid">
                            Users
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ca41c338-2a4d-48d3-8985-d5ae6fbd913b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fbfdc4b3-619b-4659-820c-48f61b25faf7?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff93dfec-abd3-4d6f-85be-4305b6abd3ef?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/11970bf3-3f09-450f-9494-7ae84d765b92?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/71cca712-7c67-49ff-aa63-4baf427d38fa?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d306b798-f727-4621-b421-b307d594554f?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex grow flex-col px-5 py-6 border-b border-solid">
                            <div className="items-start self-center flex w-[124px] max-w-full flex-col">
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cdf9c052-dbd9-432d-9c9b-8912f5cf94cd?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                    className="aspect-[5.17] object-cover object-center w-full justify-center items-center overflow-hidden self-stretch grow"
                                />
                            </div>
                        </div>
                    </div>
                    <div className="items-start self-stretch flex flex-col w-[301px]">
                        <div className="text-neutral-400 text-xs font-medium leading-[150%] self-stretch items-center border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 w-full px-5 py-3.5 border-b border-solid">
                            About
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-[230px] max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Content curating app
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Brings all your news into one place
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-[193px] max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Design software
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Super lightweight design app
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-48 max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Data prediction
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    AI and machine learning data
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-[235px] max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Productivity app
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Time management and productivity
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-[201px] max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Web app integrations
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Connect web apps seamlessly
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start flex w-[234px] max-w-full flex-col ml-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Sales CRM
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Web-based sales doc management
                                </div>
                            </div>
                        </div>
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex grow flex-col px-5 py-4 border-b border-solid">
                            <div className="items-start self-stretch flex flex-col mx-1">
                                <div className="text-neutral-100 text-sm leading-[142.86%]">
                                    Automation and workflow
                                </div>
                                <div className="text-neutral-400 text-sm leading-[142.86%]">
                                    Time tracking, invoicing and expenses
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="items-start self-stretch flex flex-col w-[116px]">
                        <div className="items-center self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] bg-gray-900 flex w-full h-11 flex-col border-b border-solid" />
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <Symbol
                                className="relative flex shrink-0 flex-col box-border"
                                symbol={{
                                    data: {},
                                }}
                                onClick={(event) => {
                                    setNewField0(!newField0);
                                }}
                            />
                            <Symbol
                                className="relative flex shrink-0 flex-col box-border"
                                symbol={{
                                    data: {},
                                }}
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/40083fa3-e68b-4955-9977-da0294fc2a16?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d8606aa8-0005-4ec3-90d0-6f6dcb0e8d51?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/a9d79456-abea-4d13-96e2-d7d24227e83e?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/8548045f-67ec-4598-a1c6-02f9ff9c904b?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/3cd03125-b90f-4c47-a8b6-62f4bf519c4a?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bd53d14b-1e68-4631-bde0-63df3d203907?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e35dadf7-4007-4d9b-8c3c-e535007d5806?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0950b659-dc83-4a2b-be97-58e8de4e797c?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/8fc638dd-77db-470c-b185-af4efb4bcb19?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/de48ce9a-165f-4ce4-a68c-34ae504b3ac3?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="items-start self-stretch border-b-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full justify-between gap-5 px-5 py-7 border-b border-solid">
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/8687be9e-3935-471c-97a8-a53f5eb205c9?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/717a2121-4033-4a62-a232-bdeb660da431?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&"
                                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
                            />
                        </div>
                    </div>
                </div>
                <div className="justify-between items-start self-stretch border-[color:var(--colors-border-border-secondary,#1F242F)] flex w-full gap-5 px-5 py-3.5 border-0 border-solid max-md:max-w-full max-md:flex-wrap">
                    <div className="items-start flex gap-3 -mt-0.5">
                        <div className="text-neutral-300 text-sm font-semibold leading-[142.86%] self-stretch justify-center items-center border border-[color:var(--component-colors-components-buttons-secondary-button-secondary-border,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 w-[87px] max-w-full px-3.5 py-2 rounded-lg border-solid">
                            Previous
                        </div>
                        <div className="text-neutral-300 text-sm font-semibold leading-[142.86%] self-stretch justify-center items-center border border-[color:var(--component-colors-components-buttons-secondary-button-secondary-border,#333741)] shadow-[0px_1px_2px_0px_rgba(16,24,40,0.05)] bg-gray-900 w-[60px] max-w-full px-3.5 py-2 rounded-lg border-solid">
                            Next
                        </div>
                    </div>
                    <div className="text-neutral-300 text-sm font-medium leading-[142.86%] self-center my-auto">
                        Page 1 of 10
                    </div>
                </div>
            </div>
        </div>
    );
}
