/**
 * This code was generated by Builder.io.
 */
"use client";
import * as React from "react";

export default function Blocks() {
    const handleButtonClick = () => {
        // Handle button click event
    };

    return (
        <div className="px-5">
            <section className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div className="flex flex-col items-stretch w-3/12 max-md:w-full">
                    <button
                        className="min-w-[200px] items-start bg-sky-100 flex w-[202px] max-w-full grow flex-col mx-auto px-5 py-6 rounded-2xl max-md:mt-7"
                        onClick={handleButtonClick}
                    >
                        <div className="items-start content-center self-center flex-wrap flex w-[154px] max-w-full gap-4 rounded-lg">
                            <div className="self-center text-zinc-900 text-sm font-semibold leading-[142.86%] w-[123px] my-auto">
                                Total Projects
                            </div>
                            <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/2847199c-98f6-4057-a23f-95d58ebc0ed6?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&" className="aspect-square object-cover object-center w-0 overflow-hidden shrink-0 mt-px"
                                alt="Description of the image"
                            />

                        </div>
                        <div className="justify-between items-start content-center gap-y-2 self-center flex-wrap flex w-[154px] max-w-full gap-5 mt-2 rounded-lg">
                            <div className="self-stretch text-zinc-900 text-2xl font-semibold leading-[150%]">
                                29
                            </div>
                            <div className="items-start content-center flex-wrap self-center flex gap-1 my-auto rounded-lg">
                                <div className="self-stretch text-zinc-900 text-xs leading-[150%]">
                                    +11.01%
                                </div>
                                <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/f191da2d-60b3-4f5e-b092-77d2985fe1db?apiKey=3cf1db2ab1694ce4be6d4ee2ec473197&" className="aspect-square object-cover object-center w-4 overflow-hidden shrink-0 mt-px"
                                    alt="Image description"
                                />
                            </div>
                        </div>
                    </button>
                </div>
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full">
                    <button
                        className="min-w-[200px] items-start bg-slate-200 flex w-[202px] max-w-full grow flex-col mx-auto px-5 py-6 rounded-2xl max-md:mt-7"
                        onClick={handleButtonClick}
                    >
                        <div className="items-start content-center self-center flex-wrap flex w-[154px] max-w-full gap-4 rounded-lg">
                            <div className="self-center text-zinc-900 text-sm font-semibold leading-[142.86%] w-[123px] my-auto">
                                Total Tasks
                            </div>
                            <img
                                loading="lazy"
                                srcSet="..."
                                className="aspect-square object-cover object-center w-6 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="justify-between items-start content-center gap-y-2 self-center flex-wrap flex w-[154px] max-w-full gap-5 mt-2 rounded-lg">
                            <div className="self-stretch text-zinc-900 text-2xl font-semibold leading-[150%]">
                                715
                            </div>
                            <div className="items-start content-center flex-wrap self-center flex gap-1 my-auto rounded-lg">
                                <div className="self-stretch text-zinc-900 text-xs leading-[150%]">
                                    -0.03%
                                </div>
                                <img
                                    loading="lazy"
                                    srcSet="..."
                                    className="aspect-square object-cover object-center w-4 overflow-hidden shrink-0 mt-px"
                                />
                            </div>
                        </div>
                    </button>
                </div>
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full">
                    <button
                        className="min-w-[200px] items-start bg-sky-100 flex w-[202px] max-w-full grow flex-col mx-auto px-5 py-6 rounded-2xl max-md:mt-7"
                        onClick={handleButtonClick}
                    >
                        <div className="items-start content-center self-center flex-wrap flex w-[154px] max-w-full gap-4 rounded-lg">
                            <div className="self-center text-zinc-900 text-sm font-semibold leading-[142.86%] w-[123px] my-auto">
                                Members
                            </div>
                            <img
                                loading="lazy"
                                srcSet="..."
                                className="aspect-square object-cover object-center w-6 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="justify-between items-start content-center gap-y-2 self-center flex-wrap flex w-[154px] max-w-full gap-5 mt-2 rounded-lg">
                            <div className="self-stretch text-zinc-900 text-2xl font-semibold leading-[150%]">
                                31
                            </div>
                            <div className="items-start content-center flex-wrap self-center flex gap-1 my-auto rounded-lg">
                                <div className="self-stretch text-zinc-900 text-xs leading-[150%]">
                                    +15.03%
                                </div>
                                <img
                                    loading="lazy"
                                    srcSet="..."
                                    className="aspect-square object-cover object-center w-4 overflow-hidden shrink-0 mt-px"
                                />
                            </div>
                        </div>
                    </button>
                </div>
                <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full">
                    <button
                        className="min-w-[200px] items-start bg-slate-200 flex w-[202px] max-w-full grow flex-col mx-auto px-5 py-6 rounded-2xl max-md:mt-7"
                        onClick={handleButtonClick}
                    >
                        <div className="items-start content-center self-center flex-wrap flex w-[154px] max-w-full gap-4 rounded-lg">
                            <div className="self-center text-zinc-900 text-sm font-semibold leading-[142.86%] w-[123px] my-auto">
                                Productivity
                            </div>
                            <img
                                loading="lazy"
                                srcSet="..."
                                className="aspect-square object-cover object-center w-6 overflow-hidden shrink-0"
                            />
                        </div>
                        <div className="justify-between items-start content-center gap-y-2 self-center flex-wrap flex w-[154px] max-w-full gap-5 mt-2 rounded-lg">
                            <div className="self-stretch text-zinc-900 text-2xl font-semibold leading-[150%]">
                                93.8%
                            </div>
                            <div className="items-start content-center flex-wrap self-center flex gap-1 my-auto rounded-lg">
                                <div className="self-stretch text-zinc-900 text-xs leading-[150%]">
                                    +6.08%
                                </div>
                                <img
                                    loading="lazy"
                                    srcSet="..."
                                    className="aspect-square object-cover object-center w-4 overflow-hidden shrink-0 mt-px"
                                />
                            </div>
                        </div>
                    </button>
                </div>
            </section>
        </div>
    );
}
