/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Sidebar() {
  return (
    <nav className="items-center border-r-[color:var(--black-10,rgba(255,255,255,0.10))] flex flex-col bg-zinc-900 px-4 border-r border-solid">
      <section className="self-stretch flex flex-col mt-6">
        <div className="items-start content-center flex-wrap flex w-[172px] max-w-full gap-2 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-6 overflow-hidden shrink-0"
          />
          <a
            href="#"
            className="self-center text-white text-sm leading-[142.86%] w-[151px] my-auto"
          >
            ByeWind
          </a>
        </div>
        <div className="items-start flex w-[180px] max-w-full flex-col mt-5 px-2 py-0.5">
          <div className="items-start content-center flex-wrap flex w-36 max-w-full justify-between gap-5 mt-0.5 rounded-lg">
            <div className="self-stretch text-white text-opacity-40 text-center text-sm leading-[142.86%]">
              Favorites
            </div>
            <div className="self-stretch text-white text-opacity-20 text-center text-sm leading-[142.86%]">
              Recently
            </div>
          </div>
          <div className="items-start content-center flex-wrap flex w-[164px] max-w-full gap-1 mt-3 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[155px]"
            >
              Overview
            </a>
          </div>
          <div className="items-start content-center flex-wrap flex w-[164px] max-w-full gap-1 mt-3 -mb-0.5 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[155px]"
            >
              Projects
            </a>
          </div>
        </div>
        <div className="items-start flex w-[180px] max-w-full flex-col mt-9 py-0.5">
          <div className="self-center text-white text-opacity-40 text-sm leading-[142.86%] w-[156px] max-w-full -mt-0.5">
            Dashboards
          </div>
          <div className="items-start content-center self-stretch flex-wrap bg-white bg-opacity-10 flex w-full justify-between gap-2 mt-2 pr-2 py-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
              />
              <a
                href="#"
                className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
              >
                Default
              </a>
            </div>
          </div>
          <div className="items-start content-center self-center flex-wrap flex w-[164px] max-w-full gap-1 mt-2 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
            />
            <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
              />
              <a
                href="#"
                className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
              >
                eCommerce
              </a>
            </div>
          </div>
          <div className="items-start content-center self-center flex-wrap flex w-[164px] max-w-full gap-1 mt-3 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
            />
            <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
              />
              <a
                href="#"
                className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
              >
                Projects
              </a>
            </div>
          </div>
          <div className="items-start content-center self-center flex-wrap flex w-[164px] max-w-full gap-1 mt-3 mb-0.5 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
            />
            <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
              <img
                loading="lazy"
                srcSet="..."
                className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
              />
              <a
                href="#"
                className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
              >
                Online Courses
              </a>
            </div>
          </div>
        </div>
      </section>
      <section className="items-start flex w-[180px] max-w-full grow flex-col mt-8 px-2 py-0.5">
        <div className="self-center text-white text-opacity-40 text-sm leading-[142.86%] w-[156px] max-w-full -mt-0.5">
          Pages
        </div>
        <div className="items-start content-center self-stretch flex-wrap flex justify-between gap-1 mt-3 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
          />
          <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
            >
              User Profile
            </a>
          </div>
        </div>
        <a
          href="#"
          className="text-white text-sm leading-[142.86%] w-[120px] max-w-full mt-3"
        >
          Overview
        </a>
        <a
          href="#"
          className="text-white text-sm leading-[142.86%] w-[120px] max-w-full mt-3"
        >
          Projects
        </a>
        <a
          href="#"
          className="text-white text-sm leading-[142.86%] w-[120px] max-w-full mt-3"
        >
          Campaigns
        </a>
        <a
          href="#"
          className="text-white text-sm leading-[142.86%] w-[120px] max-w-full mt-3"
        >
          Documents
        </a>
        <a
          href="#"
          className="text-white text-sm leading-[142.86%] w-[120px] max-w-full mt-3"
        >
          Followers
        </a>
        <div className="items-start content-center self-stretch flex-wrap flex justify-between gap-1 mt-3 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
          />
          <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
            >
              Account
            </a>
          </div>
        </div>
        <div className="items-start content-center self-stretch flex-wrap flex justify-between gap-1 mt-3 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
          />
          <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
            >
              Corporate
            </a>
          </div>
        </div>
        <div className="items-start content-center self-stretch flex-wrap flex justify-between gap-1 mt-3 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
          />
          <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
            >
              Blog
            </a>
          </div>
        </div>
        <div className="items-start content-center self-stretch flex-wrap flex justify-between gap-1 mt-3 mb-0.5 rounded-lg">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-square object-cover object-center w-4 overflow-hidden self-center shrink-0 my-auto"
          />
          <div className="items-start content-center flex-wrap self-stretch flex justify-between gap-1 rounded-lg">
            <img
              loading="lazy"
              srcSet="..."
              className="aspect-square object-cover object-center w-5 overflow-hidden shrink-0"
            />
            <a
              href="#"
              className="self-stretch text-white text-sm leading-[142.86%] w-[129px]"
            >
              Social
            </a>
          </div>
        </div>
      </section>
      <img
        loading="lazy"
        srcSet="..."
        className="aspect-[3.7] object-cover object-center w-[74px] justify-center items-center overflow-hidden self-center shrink-0 mt-64 mb-7 max-md:mt-52"
      />
    </nav>
  );
}
